### ISSUE TITLE
Timelapse 2016 EP on distrokid

### ISSUE THREAD

**Issue by chrisdugne** [velvetcoffee/music#12]
- [x] artwork
- [x] master winter waltz  ?
- [x] mist to rename
- [x] upload

**Comment by Leosorus** [comment]
https://www.wetransfer.com/downloads/a01a49e16e80d72d5fba13d4cb19a9e120161018180850/aab18e041f924590d7755cc8f9d0133620161018180850/da6c6b

Check. Photo de l'EP et bannieres, si besoin
