### ISSUE TITLE
Vignoble ---> Morning Love

### ISSUE THREAD

**Issue by Leosorus** [velvetcoffee/music#16]
Je t'envoie via Dropbox, ma version pour la vidéo de Gunther. 
Que du piano pour le moment. Mais pour garder l'esprit de ce qu'il voulait, il faudra par la suite incorporer des cordes. 

Pour l'instant il faut surtout un vrai morceau de piano. J'ai un bon début je pense mais il est pas assez long. J'avais une super intro hier soir... mais je l'ai zappée ce matin, j'suis dégoûté --'

Bref, tu peux voir si ça t'inspire, y mettre ta patte. Qu'on parte avec des fondations solides et efficaces :) ?

**Comment by chrisdugne** [comment]
bien inspiré ce piano, joli !

**Comment by Leosorus** [comment]
[Uploading Clicquot Mon Cul ouais.mp3.zip…]()

**Comment by Leosorus** [comment]
[Clicquot Mon Cul ouais.mp3.zip](https://github.com/velvetcoffee/music/files/560842/Clicquot.Mon.Cul.ouais.mp3.zip)

**Comment by Leosorus** [comment]
[Clicquot_MixFin.mp3.zip](https://github.com/velvetcoffee/music/files/560857/Clicquot_MixFin.mp3.zip)

**Comment by Leosorus** [comment]
[MORNING LOVE.mp3.zip](https://github.com/velvetcoffee/music/files/561718/MORNING.LOVE.mp3.zip)

Okay pour toi ? :)

**Comment by Leosorus** [comment]
http://www.mediafire.com/file/c31c38ppcbpcq9k/Morning+Love+Master+24bit.wav

Le mastering pour la musique de Cliquot. 
Faut la nommer :) j'aimais bien "Morning Love" mais bon. Si d'autres idées.
Et surtout faut payer Franck ;)

**Comment by Leosorus** [comment]
Master V2 que je préfère perso

http://www.mediafire.com/file/c9c369ebfbd1753/Morning+Love+Master+2.wav

**Comment by chrisdugne** [comment]
https://soundcloud.com/velvetcoffee/morning-love
