### ISSUE TITLE
Autumn Leaves

### ISSUE THREAD

**Issue by chrisdugne** [velvetcoffee/music#2]

**Comment by Leosorus** [comment]
[Autumn Leaves.mp3.zip](https://github.com/velvetcoffee/music/files/511468/Autumn.Leaves.mp3.zip)

Voilà :) écoute ça mon p'tit cooomme c'est jôôôôliiii :)
Ce que j'ai fait de mieux pour l'instant, à mon avis. En tout cas ce que je préfère .

**Comment by chrisdugne** [comment]
🙀 
la fin donne tellement de frissons 🎵

**Comment by Leosorus** [comment]
tu pourras m'électroser tout ça? :) surtout au début?
BPM150
en 3/4

**Comment by chrisdugne** [comment]
bon, quelques idées, mais rien de dingue.. tu tries et cales des vrais sons pour voir ?
je te file le projet sur dropbox
[leaves-1.0.1.mp3.zip](https://github.com/velvetcoffee/music/files/517214/leaves-1.0.1.mp3.zip)

**Comment by chrisdugne** [comment]
j'ai tout viré cest de la 💩 
[leaves-1.0.2.mp3.zip](https://github.com/velvetcoffee/music/files/517694/leaves-1.0.2.mp3.zip)
je lai bien mieux ressenti là

**Comment by chrisdugne** [comment]
avec le debut
[leaves-1.0.3.mp3.zip](https://github.com/velvetcoffee/music/files/518238/leaves-1.0.3.mp3.zip)
va falloir nous mixer ca aux petits oignons coco

**Comment by Leosorus** [comment]
[Autumn Leaves_Mix9oct.mp3.zip](https://github.com/velvetcoffee/music/files/518371/Autumn.Leaves_Mix9oct.mp3.zip)
J'ai enlevé quelques trucs, ajouté d'autres trucs, modifié certains trucs et mixé le tout.

Alors? :)

**Comment by Leosorus** [comment]
pff... mais même en ré écoutant là, en ayant enlevé plein de choses je trouve bien trop chargé.
C'etait presque parfait initialement franchement.

**Comment by Leosorus** [comment]
[AL.mp3.zip](https://github.com/velvetcoffee/music/files/518489/AL.mp3.zip)
Ecoute comme ça

**Comment by Leosorus** [comment]
https://soundcloud.com/velvetcoffee/autumn-leaves

Et hop ;) Le master déjà sur Soundcloud.
Thomas fais une vidéo qu'il veut appeler "Velvet Coffee" pour nous remercier :D Et ça, ça tue !!!!

**Comment by chrisdugne** [comment]
ohoh trop cool !

**Comment by chrisdugne** [comment]
https://open.spotify.com/track/0cLdALEKKvDv5P2yAVpW52
