### ISSUE TITLE
Winter Waltz

### ISSUE THREAD

**Issue by chrisdugne** [velvetcoffee/music#5]

**Comment by Leosorus** [comment]
https://www.youtube.com/watch?v=GGaUdgAp7LQ&feature=youtu.be&noredirect=1

A mettre sur le site ;)

**Comment by chrisdugne** [comment]
done https://github.com/velvetcoffee/velvetcoffee.github.io/commit/a7495b45981f0cd2a967bdf180c625e653f85e29
