### ISSUE TITLE
[Video] BlackMagic

### ISSUE THREAD

**Issue by chrisdugne** [velvetcoffee/music#7]
soundtrack for `Empara Directors cut / Test Ursa Mini 4.6K` / Pascal Délé

**Comment by chrisdugne** [comment]
le `master` dans un beau [lien](https://sonics-mastering.wetransfer.com/downloads/a063b41d11ca4d5e15a935df3d8e658920160126104820/06eb2a440b87e5150593e4eef455dcd820160126104820/3be164) :white_check_mark:

**Comment by chrisdugne** [comment]
résultat final : https://vimeo.com/154069606

**Comment by Leosorus** [comment]
https://m.facebook.com/ObjectifPhotographe/

Regarde =) plus de 40000 vues

**Comment by Leosorus** [comment]
Bonjour velvetcoffee/music,

J’aimerais que vous rejoigniez mon réseau pour partager des nouvelles et rester en contact.

Leonardo

Veuillez confirmer que vous connaissez Leonardo: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=os7IH2jH&invitationId=6203946961914118144&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eivi7k4zn%7Ejy

Vous avez reçu une invitation à rejoindre un réseau. LinkedIn utilise votre adresse e-mail pour faire des suggestions à ses utilisateurs dans des fonctionnalités telles que Les connaissez-vous ? Se désabonner ici : https://www.linkedin.com/e/v2?e=0-ivi7k4zn-jy&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHSNu8ezJPL2gAAAVhjZMuCOD9Tk6OPzVpGLNoZLge_bekNSbCFctHV_3LTVlvaY53Uhmy9eRN626zCnfHxvo-zmfzxPSz6mzWkx1hKJ1H1XfaQeh7l2rEAzxTaBA-jEbIFMpQdDkSIEa5XUF7nuHWeCk0ydB9MxfVOEWOYmNNcyhKMhPayrhmMk3SezCaxBv_P&eid=0-ivi7k4zn-jy

Cet e-mail est destiné à reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ivi7k4zn-jy&a=customerServiceUrl&ek=invite_guest

© 2016 LinkedIn Corporation, 1 000 West Maude Avenue, Sunnyvale, CA 94085, USA. LinkedIn et le logo de LinkedIn sont des marques déposées de LinkedIn.

**Comment by Leosorus** [comment]
Leonardo Villiger would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=os7IH2jH&invitationId=6203946961914118144&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-%7Ec91igl%7Eivrva69y%7E9c

View Leonardo Villiger&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=os7IH2jH&invitationId=6203946961914118144&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-%7Ec91igl%7Eivrva69y%7E9c

velvetcoffee/music,

J’aimerais vous inviter à rejoindre mon réseau professionnel sur LinkedIn.

Vous avez reçu une invitation à rejoindre un réseau. LinkedIn utilise votre adresse e-mail pour faire des suggestions à ses utilisateurs dans des fonctionnalités telles que Les connaissez-vous ? Se désabonner ici : https://www.linkedin.com/e/v2?e=-c91igl-ivrva69y-9c&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=-c91igl-ivrva69y-9c&loid=AQEXuUWTAhQJ2AAAAViHaxk-Q3hKRkcBSKF9XNS36Dwcg__B5AzB0g0aHNMTiJ8KAD1BbQSWrjuTfgoUnxNgoUHJe8UVYwT9DPQ_jxGz8DDegfp0EEnr7LO2WdC-UXOSzqmTTYAAWvCiKM3CnZELIUyxrl_tOk_lg_GIPbUA9nOfBIvm_G8WdRbtSv1YQUm29r3J

Cet e-mail est destiné à reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-c91igl-ivrva69y-9c&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Leosorus** [comment]
Hi ,

Leonardo Villiger would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=os7IH2jH&invitationId=6203946961914118144&trk=eml-second_guest_reminder_01-hero-120-accept_text&trkEmail=eml-second_guest_reminder_01-hero-120-accept_text-null-%7Ec91igl%7Eiw1vc5xe%7Eff

View Leonardo Villiger&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=os7IH2jH&invitationId=6203946961914118144&trk=eml-second_guest_reminder_01-hero-3-profile_text&trkEmail=eml-second_guest_reminder_01-hero-3-profile_text-null-%7Ec91igl%7Eiw1vc5xe%7Eff

velvetcoffee/music,

J’aimerais vous inviter à rejoindre mon réseau professionnel sur LinkedIn.





Vous avez reçu une invitation à rejoindre un réseau. LinkedIn utilise votre adresse e-mail pour faire des suggestions à ses utilisateurs dans des fonctionnalités telles que Les connaissez-vous ? Se désabonner ici : https://www.linkedin.com/e/v2?e=-c91igl-iw1vc5xe-ff&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=122&m=unsub&ts=HTML&eid=-c91igl-iw1vc5xe-ff&loid=AQEs2B03E1vP4QAAAVirnEFlMSaoEJEiboqDD4XGnpMCl-ay5Pz7Jv-EvO1l6xVbThajJ5NQNMvSPE5_PIZIYu8KeHkKy0kMRIlzjhYtUOxsYSg8eCkT2ueHES3EKPMzl_OGysAZeMO1SI4wZgGEoUsIf8MNHgLZBiCTvaN3DXQxG1WY0kP-xXKfXwpvDyIk5a6WoQFZQ5AA3rYEiYkwcCmd715RPA

Cet e-mail est destiné à reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-c91igl-iw1vc5xe-ff&a=customerServiceUrl&ek=second_guest_reminder_01

© 2016 LinkedIn Corporation, 1 000 West Maude Avenue, Sunnyvale, CA 94085, USA. LinkedIn et le logo de LinkedIn sont des marques déposées de LinkedIn.
